# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-19 11:39
from __future__ import unicode_literals

from django.db import migrations, models
import people.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duke_id', models.CharField(max_length=20)),
                ('student_name', models.CharField(max_length=200)),
                ('course', models.IntegerField(choices=[(1, 'MEM'), (2, 'MENG')])),
                ('description', models.CharField(max_length=142)),
                ('picture', models.ImageField(upload_to=b'')),
                ('name_audio', models.FileField(upload_to=b'', validators=[people.models.validate_file_extension])),
            ],
        ),
    ]
