# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 05:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duke_id', models.CharField(max_length=20)),
                ('student_name', models.CharField(max_length=200)),
                ('course', models.IntegerField(choices=[(1, 'MEM'), (2, 'MENG')])),
                ('picture', models.FileField(upload_to=b'')),
                ('name_audio', models.ImageField(upload_to=b'')),
            ],
        ),
    ]
